# Generated by Django 2.1.7 on 2019-03-31 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BackgroundJobs', '0002_auto_20190331_1918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='networksnifferscanner',
            name='is_sniffer',
            field=models.IntegerField(null=True),
        ),
    ]
