#                                                READ ME
#====================================================================================================
# - Time is measure in seconds.
# - Changes in database configurations require must be followed by following steps.
#     -Importing database structure into mysql.
#     -Django database migration.
# - Minimum scan intervals in port scanning and sniffer scan may result in network congestion.
# - Alpha and omega define the range any kind of port scanning where the define port numbers.
#====================================================================================================

#IMPORTATN:You have to change database configurations
#These configurations automatically change the config
#in setting.py file of django server
database:
  host: localhost
  port: 3306
  username: root
  password: admin
  schema: mib

#topology configuration target topology mapping module.
#scan intervel decide after how much time network must
#be scanned for changes
topology:
  scan_intervel: 50

#portscan configurations target OpenPortScanner module 
#scan intervel decide after how much time devices must
#be scanned for open ports
#alpha and omega are the range for port scan.
#portscan configurations target PacketSnifferDetection
#module scan intervel decide after how much time netwo
#-rk must be scanned for packet sniffer
#alpha and omega are the range for port scan.
portscan:
  scan_intervel: 10

#packetflow configurations target PacketFlowCapture Mo
#-dule port dedicate the port at which you want to col
#-lect the packet flow.
#Caution: port must not be assign to anyother program
#Else it can lead to program malfunction.
packetflow:
  host_ip: 192.168.1.10
  port: 3308

packetvis:
  intervel: 5
  packet_eql: 5
