#                                                READ ME
#====================================================================================================
# - Time is measure in seconds.
# - Changes in database configurations require must be followed by following steps.
#     -Importing database structure into mysql.
#     -Django database migration.
# - Minimum scan intervals in port scanning and sniffer scan may result in network congestion.
# - Alpha and omega define the range any kind of port scanning where the define port numbers.
#====================================================================================================

#IMPORTATN:You have to change database configurations
#These configurations automatically change the config
#in setting.py file of django server
database:
  host: localhost
  port: 3306
  username: root
  password: admin
  schema: mib
#packetflow configurations target PacketFlowCapture Mo
#-dule port dedicate the port at which you want to col
#-lect the packet flow.
#Caution: port must not be assign to anyother program
#Else it can lead to program malfunction.
packetflow:
  host_ip: 192.168.1.10
  port: 3308