# Generated by Django 2.1.7 on 2019-03-24 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TopologyBridge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(blank=True, max_length=100, null=True)),
                ('bridge', models.CharField(blank=True, max_length=100, null=True)),
                ('vlan', models.CharField(blank=True, max_length=100, null=True)),
                ('type', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'topology_bridge',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TopologyDevices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('child_ip', models.CharField(blank=True, max_length=50, null=True)),
                ('age', models.CharField(blank=True, max_length=50, null=True)),
                ('hard_address', models.CharField(blank=True, max_length=50, null=True)),
                ('interface', models.CharField(blank=True, max_length=100, null=True)),
                ('parent_ip', models.CharField(blank=True, max_length=50, null=True)),
                ('parent_type', models.CharField(blank=True, max_length=50, null=True)),
                ('protocol', models.CharField(blank=True, max_length=100, null=True)),
                ('type', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'topology_devices',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TopologyHardware',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent_ip', models.CharField(blank=True, max_length=45, null=True)),
                ('vlan', models.CharField(blank=True, max_length=45, null=True)),
                ('mac', models.CharField(blank=True, max_length=45, null=True)),
                ('type', models.CharField(blank=True, max_length=45, null=True)),
                ('port', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'topology_hardware',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TopologySsh',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=100, unique=True)),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('port', models.CharField(max_length=10)),
                ('type', models.CharField(blank=True, max_length=45, null=True)),
                ('host_bits', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'topology_ssh',
                'managed': False,
            },
        ),
    ]
