# Generated by Django 2.1.7 on 2019-03-24 08:14

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceInfo',
            fields=[
                ('mac_address', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('ip_address', models.CharField(blank=True, max_length=20, null=True)),
                ('mask', models.CharField(blank=True, max_length=20, null=True)),
                ('sys_info', django_mysql.models.JSONField(blank=True, default=dict, null=True)),
            ],
            options={
                'db_table': 'device_info',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Execute',
            fields=[
                ('mac_address', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('boot_flag', models.IntegerField()),
                ('service_flag', models.IntegerField()),
                ('kill_flag', models.IntegerField()),
                ('script_flag', models.IntegerField()),
                ('port_flag', models.IntegerField()),
                ('boot_command', models.CharField(blank=True, max_length=10, null=True)),
                ('service_name', models.CharField(blank=True, max_length=50, null=True)),
                ('kill_name', models.CharField(blank=True, max_length=50, null=True)),
                ('script', models.TextField(blank=True, null=True)),
                ('portno', models.IntegerField(blank=True, null=True)),
                ('online', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'execute',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OpenPorts',
            fields=[
                ('mac_address', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('json', django_mysql.models.JSONField(blank=True, default=dict, null=True)),
                ('number', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'open_ports',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProcessInfo',
            fields=[
                ('mac_address', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('process_info', django_mysql.models.JSONField(blank=True, default=dict, null=True)),
                ('number', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'process_info',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ServicesInfo',
            fields=[
                ('mac_address', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('services_info', django_mysql.models.JSONField(blank=True, default=dict, null=True)),
                ('total', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'services_info',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('token', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('mac', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'token',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TokenStore',
            fields=[
                ('token', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('is_taken', models.IntegerField()),
            ],
            options={
                'db_table': 'token_store',
                'managed': False,
            },
        ),
    ]
